package com.example.vx

/** Hindi labels for the fixed COCO vocabulary bundled with the offline detector. */
object HindiObjectLabels {
    private val labels = mapOf(
        "person" to "व्यक्ति",
        "bicycle" to "साइकिल",
        "car" to "कार",
        "motorbike" to "मोटरसाइकिल",
        "aeroplane" to "हवाई जहाज़",
        "bus" to "बस",
        "train" to "ट्रेन",
        "truck" to "ट्रक",
        "boat" to "नाव",
        "traffic light" to "ट्रैफिक लाइट",
        "fire hydrant" to "फायर हाइड्रेंट",
        "stop sign" to "रुकने का संकेत",
        "parking meter" to "पार्किंग मीटर",
        "bench" to "बेंच",
        "bird" to "पक्षी",
        "cat" to "बिल्ली",
        "dog" to "कुत्ता",
        "horse" to "घोड़ा",
        "sheep" to "भेड़",
        "cow" to "गाय",
        "elephant" to "हाथी",
        "bear" to "भालू",
        "zebra" to "ज़ेब्रा",
        "giraffe" to "जिराफ़",
        "backpack" to "बैग",
        "umbrella" to "छाता",
        "handbag" to "हैंडबैग",
        "tie" to "टाई",
        "suitcase" to "सूटकेस",
        "frisbee" to "फ्रिस्बी",
        "skis" to "स्की",
        "snowboard" to "स्नोबोर्ड",
        "sports ball" to "खेल की गेंद",
        "kite" to "पतंग",
        "baseball bat" to "बेसबॉल बैट",
        "baseball glove" to "बेसबॉल दस्ताना",
        "skateboard" to "स्केटबोर्ड",
        "surfboard" to "सर्फ़बोर्ड",
        "tennis racket" to "टेनिस रैकेट",
        "bottle" to "बोतल",
        "wine glass" to "गिलास",
        "cup" to "कप",
        "fork" to "कांटा",
        "knife" to "चाकू",
        "spoon" to "चम्मच",
        "bowl" to "कटोरा",
        "banana" to "केला",
        "apple" to "सेब",
        "sandwich" to "सैंडविच",
        "orange" to "संतरा",
        "broccoli" to "ब्रोकोली",
        "carrot" to "गाजर",
        "hot dog" to "हॉट डॉग",
        "pizza" to "पिज़्ज़ा",
        "donut" to "डोनट",
        "cake" to "केक",
        "chair" to "कुर्सी",
        "sofa" to "सोफ़ा",
        "pottedplant" to "गमले का पौधा",
        "bed" to "बिस्तर",
        "diningtable" to "खाने की मेज़",
        "toilet" to "शौचालय",
        "tvmonitor" to "टीवी",
        "laptop" to "लैपटॉप",
        "mouse" to "माउस",
        "remote" to "रिमोट",
        "cell phone" to "मोबाइल फोन",
        "microwave" to "माइक्रोवेव",
        "oven" to "ओवन",
        "toaster" to "टोस्टर",
        "sink" to "सिंक",
        "refrigerator" to "फ्रिज",
        "book" to "किताब",
        "clock" to "घड़ी",
        "vase" to "फूलदान",
        "scissors" to "कैंची",
        "teddy bear" to "टेडी बियर",
        "hair drier" to "हेयर ड्रायर",
        "toothbrush" to "टूथब्रश"
    )

    fun labelFor(modelLabel: String): String =
        labels[modelLabel.trim().lowercase()] ?: modelLabel
}
